// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZP1J4h86vNwoskaBheawpkuyPTODF7qE',
    appId: '1:885016612643:web:0d45ca481a86a74e100696',
    messagingSenderId: '885016612643',
    projectId: 'swift-talk-2',
    authDomain: 'swift-talk-2.firebaseapp.com',
    storageBucket: 'swift-talk-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUQE8oMJ5BnTzANltMDCUJVrujyKFqOk',
    appId: '1:885016612643:android:b806c2ea3d86fd62100696',
    messagingSenderId: '885016612643',
    projectId: 'swift-talk-2',
    storageBucket: 'swift-talk-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiF4grUvrNppwI9dPybvSCDtIWYhNzeH0',
    appId: '1:885016612643:ios:cc5f322271e28e94100696',
    messagingSenderId: '885016612643',
    projectId: 'swift-talk-2',
    storageBucket: 'swift-talk-2.firebasestorage.app',
    iosBundleId: 'com.example.swiftTalk2',
  );
}
